### ISSUE TITLE
Problem with few folders with the same name

### ISSUE THREAD

**Issue by nchorniy** [dej10/strapi-plugin-file-system#3]
Hello @dej10 ,
First I would like to thank you for this plugin. I appreciate your efforts in making this useful plugin but during work of my team with it we will discovered some problem. It is no way to retrieve proper folder if we have few folders with the same name in media library. API always return only the first folder. So I would like suggest following solution: add new API which will retrieve folder by path. And I have already did it in this pull request: https://github.com/dej10/strapi-plugin-file-system/pull/2 Please review.

**Comment by dej10** [comment]
Hi @nchorniy,

I appreciate your feedback and contribution to the plugin. I'll take a look at your pull request to review and test the changes you've made. Thank you for your input, and I'll get back to you with any feedback or comments on the PR.

**Comment by nchorniy** [comment]
Hi @dej10 ,
How are you? Do you have any news? Any concerns, questions or maybe some suggestions to make some improvements which need to do in my pull-request?

**Comment by dej10** [comment]
This has been merged in #2
