### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jmather-aipm** [dej10/strapi-plugin-file-system#6]
I don't see File-system in the Users & Permissions Plugin > Roles list of endpoints and permissions.  Is there any chance of registering the File-system endpoint with the Users & Permissions Plugin so that we can prevent access to File-system if not properly authenticated?

**Comment by tranhuuphucuong** [comment]
@jmather-aipm I was concern about having the endpoint being public as well. After doing some searching, I ended up forking the plugin and implement it locally in my project. For the authentication I convert it to `content-api`. The routes look something like this:

```js
export default {
  "content-api": {
    type: "content-api",
    routes: [
      {
        method: 'GET',
        path: '/docs/:folderName',
        handler: 'fs.getOne',
          config: {
          policies: [],
        },
      }
    ],
  },
};
```

Note that now the endpoint will be behind your api: `localhost:1337/api/file-system/docs/:folderName` and you need to config your permission of "this api" in your strapi admin to consume it

**Comment by jmather-aipm** [comment]
@tranhuuphucuong Hey cool, thanks for the info!  I actually ended up just removing the plugin and creating my own custom endpoints to interact with the file system via the query service API.  I think that both approaches are valid.
