### ISSUE TITLE
Compatibility with strapi 5

### ISSUE THREAD

**Issue by owenmorales5** [dej10/strapi-plugin-file-system#7]
I want install the plugin with strapi 5 but i have issues with the versions 
![image](https://github.com/user-attachments/assets/58117383-6923-489c-bffb-775dfb196ecd)

**Comment by javiersalazardev** [comment]
You can solved it using an override, this works for me: 

put this in the package.json and then install the package
`
  "overrides": {
    "strapi-plugin-file-system": {
      "@strapi/strapi": "5.0.5"
    }
  }
`

![image](https://github.com/user-attachments/assets/0b7f0ac7-9d4c-494a-9d6a-4bb7fca94275)
